export const changeAuth = 'changeAuth'
export const changeUsers = 'changeUsers'
export const changeTasks = 'changeTasks'
export const changeAutoComplitTasks = 'changeAutoComplitTasks'
export const changeWorkItems = 'changeWorkItems'